services:
  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    networks:
      - caddy
      - ntfy
    command:
      - serve
    environment:
      - TZ=America/New_York # optional: Change to your desired timezone
    #user: UID:GID # optional: Set custom user/group or uid/gid
    volumes:
      - ./cache/ntfy:/var/cache/ntfy
      - ./etc/ntfy:/etc/ntfy
    # ports:
    # - 8443:80
    restart: unless-stopped
networks:
  caddy:
    external: true
  ntfy:
    external: true
