services:
  npm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy
    restart: unless-stopped
    networks:
      - npm
    ports:
      # These ports are in format :
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port - comment out once you set up a proxy host for admin page
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  npm:
    external: true
